---
--- Generated by Luanalysis
--- Created by DELL_.
--- DateTime: 2024-5月-04 18:53
---

-- 将逗号分隔的字符串转换为table
local function stringToTable(str)
    local result = {}
    for token in string.gmatch(str, "[^,]+") do
        table.insert(result, token)
    end
    return result
end

-- 1. 移除收件箱的用户id
local userId = ARGV[1]
local key = 'feed:' .. userId
-- 2. 移除的帖子id集合
local blogIdsStr = ARGV[2]
-- 3. 转换成table
local blogIds = stringToTable(blogIdsStr)
-- 4. 实际移除个数
local removedCount = 0
-- 5. 遍历移除
for i, blogId in ipairs(blogIds) do
    removedCount = removedCount + redis.call('ZREM', key, blogId)
end
if removedCount == #blogIds then
    return "All members removed successfully, total count:" .. removedCount
else
    return "Some members were not found or not removed"
end